apiVersion: v1
kind: Service
metadata:
  name: tomcat-example
spec:
  type: NodePort
  ports:
  - name: "vote-service"
    port: 8080
    targetPort: 8080
    nodePort: 31001
  selector:
    app: tomcat-example
