apiVersion: v1
kind: Service
metadata:
  name: tomcat-example
spec:
  type: NodePort
  ports:
  - name: tomcat-example
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 31001
  selector:
    app: tomcat-example
